name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if it's not "main"

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Check out your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (if your project uses Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use the appropriate Node.js version

      # Step 3: Inject CLIENT_ID and CLIENT_SECRET into a config.js file
      - name: Create config.js
        run: |
          echo "const CLIENT_ID = '${{ secrets.CLIENT_ID }}';" > config.js
          echo "const CLIENT_SECRET = '${{ secrets.CLIENT_SECRET }}';" >> config.js

      # Step 4: Build your project (if applicable)
      - name: Build project
        run: |
          npm install  # Install dependencies if you have a package.json
          npm run build  # Replace with your build command if applicable

      # Step 5: Upload the build artifacts to GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # Replace with your build output directory (e.g., ./dist)

      # Step 6: Deploy to GitHub Pages
      - name: Deploy
        uses: actions/deploy-pages@v4
